### ISSUE TITLE
app does not support startTLS

### ISSUE THREAD

**Issue by mwuerr** [bitfireAT/cadroid#10]
it seems this app does not support start tls.
When accessing a server with ssl disabled it issues an sslv3 error message
ssl handshake aborted. Failure in ssl library 
routines:SSL23 get server helo : sslv3

ssl is disabled on my server due to current bugs in ssl.

**Comment by rfc2822** [comment]
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including detailled steps to reproduce the issue and [verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs).

DAVdroid supports TLS 1, 1.1 and 1.2 (if available on your device); SSLv3 is blocked due to security reasons.

So I don't know whats the problem, so please provide more information including steps to reproduce (see above).

**Comment by mwuerr** [comment]
sorry, this was a server side issue. We disabled the sslv3 related ciphers in addition to disabling the protocol. Reenabling (most of ) the ciphers solved the issue.
